// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHpZ65xUncxHVvjW3rfik_Q4wDjaQzuCg',
    appId: '1:576773819258:web:bebfd2bdcc5e0682bb24c3',
    messagingSenderId: '576773819258',
    projectId: 'my-gallery-app-1c97b',
    authDomain: 'my-gallery-app-1c97b.firebaseapp.com',
    storageBucket: 'my-gallery-app-1c97b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJWEcWYRm5fLKvWlan7l3oznp35TdBO8',
    appId: '1:576773819258:android:1f6a7cfe2d297504bb24c3',
    messagingSenderId: '576773819258',
    projectId: 'my-gallery-app-1c97b',
    storageBucket: 'my-gallery-app-1c97b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzHYEhiDzgnA0wVZrjIB_8jqvlNXh2Qg',
    appId: '1:576773819258:ios:f161c8d9b321c4e6bb24c3',
    messagingSenderId: '576773819258',
    projectId: 'my-gallery-app-1c97b',
    storageBucket: 'my-gallery-app-1c97b.appspot.com',
    iosBundleId: 'com.example.myGalleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzHYEhiDzgnA0wVZrjIB_8jqvlNXh2Qg',
    appId: '1:576773819258:ios:6ee4ad61219d9ed6bb24c3',
    messagingSenderId: '576773819258',
    projectId: 'my-gallery-app-1c97b',
    storageBucket: 'my-gallery-app-1c97b.appspot.com',
    iosBundleId: 'com.example.myGalleryApp.RunnerTests',
  );
}
